/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	appscodecomv1alpha1 "github.com/sheikh-arman/controller-appscode-api/pkg/apis/appscode.com/v1alpha1"
	versioned "github.com/sheikh-arman/controller-appscode-api/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sheikh-arman/controller-appscode-api/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/sheikh-arman/controller-appscode-api/pkg/client/listers/appscode.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EmployeeInformer provides access to a shared informer and lister for
// Employees.
type EmployeeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EmployeeLister
}

type employeeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEmployeeInformer constructs a new informer for Employee type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEmployeeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEmployeeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEmployeeInformer constructs a new informer for Employee type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEmployeeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppscodeV1alpha1().Employees(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppscodeV1alpha1().Employees(namespace).Watch(context.TODO(), options)
			},
		},
		&appscodecomv1alpha1.Employee{},
		resyncPeriod,
		indexers,
	)
}

func (f *employeeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEmployeeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *employeeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&appscodecomv1alpha1.Employee{}, f.defaultInformer)
}

func (f *employeeInformer) Lister() v1alpha1.EmployeeLister {
	return v1alpha1.NewEmployeeLister(f.Informer().GetIndexer())
}
