/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/sheikh-arman/controller-appscode-api/pkg/apis/appscode.com/v1alpha1"
	appscodecomv1alpha1 "github.com/sheikh-arman/controller-appscode-api/pkg/client/applyconfiguration/appscode.com/v1alpha1"
	scheme "github.com/sheikh-arman/controller-appscode-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EmployeesGetter has a method to return a EmployeeInterface.
// A group's client should implement this interface.
type EmployeesGetter interface {
	Employees(namespace string) EmployeeInterface
}

// EmployeeInterface has methods to work with Employee resources.
type EmployeeInterface interface {
	Create(ctx context.Context, employee *v1alpha1.Employee, opts v1.CreateOptions) (*v1alpha1.Employee, error)
	Update(ctx context.Context, employee *v1alpha1.Employee, opts v1.UpdateOptions) (*v1alpha1.Employee, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Employee, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.EmployeeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Employee, err error)
	Apply(ctx context.Context, employee *appscodecomv1alpha1.EmployeeApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Employee, err error)
	EmployeeExpansion
}

// employees implements EmployeeInterface
type employees struct {
	client rest.Interface
	ns     string
}

// newEmployees returns a Employees
func newEmployees(c *AppscodeV1alpha1Client, namespace string) *employees {
	return &employees{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the employee, and returns the corresponding employee object, and an error if there is any.
func (c *employees) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Employee, err error) {
	result = &v1alpha1.Employee{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("employees").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Employees that match those selectors.
func (c *employees) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EmployeeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.EmployeeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("employees").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested employees.
func (c *employees) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("employees").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a employee and creates it.  Returns the server's representation of the employee, and an error, if there is any.
func (c *employees) Create(ctx context.Context, employee *v1alpha1.Employee, opts v1.CreateOptions) (result *v1alpha1.Employee, err error) {
	result = &v1alpha1.Employee{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("employees").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(employee).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a employee and updates it. Returns the server's representation of the employee, and an error, if there is any.
func (c *employees) Update(ctx context.Context, employee *v1alpha1.Employee, opts v1.UpdateOptions) (result *v1alpha1.Employee, err error) {
	result = &v1alpha1.Employee{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("employees").
		Name(employee.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(employee).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the employee and deletes it. Returns an error if one occurs.
func (c *employees) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("employees").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *employees) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("employees").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched employee.
func (c *employees) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Employee, err error) {
	result = &v1alpha1.Employee{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("employees").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied employee.
func (c *employees) Apply(ctx context.Context, employee *appscodecomv1alpha1.EmployeeApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Employee, err error) {
	if employee == nil {
		return nil, fmt.Errorf("employee provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(employee)
	if err != nil {
		return nil, err
	}
	name := employee.Name
	if name == nil {
		return nil, fmt.Errorf("employee.Name must be provided to Apply")
	}
	result = &v1alpha1.Employee{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("employees").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
